### ISSUE TITLE
Monokle window goes black

### ISSUE THREAD

**Issue by DanPhonovation** [kubeshop/monokle#1690]
**Describe the bug**
Fresh install. Configured an empty template. Pointed it at my kubeconfig. As soon as the window loads, there is a brief moment I see the initial screen and then except for the "File" menus, the window goes black and I'm unable to do anything but quit and try again.

Windows 10

**Comment by devcatalin** [comment]
Hi @DanPhonovation , we will release the 1.7 version today which includes stability improvements and a couple of new features. I'll reply here when the installer is officially released so you can try it and let us know if you still have any problems. Thank you!

**Comment by dimonlex** [comment]
Hi DanPhonavation, did 1.7 released yesterday help?

**Comment by torbenbn** [comment]
Hi all, I see the same behavior in 1.7.0: 

Monokle starts up, displays the splash animation and then the main window appears looking normal.  After a few seconds I see a Folder Import notification and then the window goes all black.  

The menu bar is still visible and functional.  If I select View > Reload it does the same thing of drawing the window, displaying the notification and turning black.

I'm also on Windows 10 FWIIW.  Slight edge-case'iness of my setup is that I run Monokle via RDP on a VM installation of Windows.  

cheers,
Torben

**Comment by dimonlex** [comment]
Thanks for the those details.  Any chance you can run it without an RDP and a VM?  Not sure we have that set up for replication.  If not could you do a live session with one of the Developers?

**Comment by olensmar** [comment]
thanks for reporting @torbenbn @DanPhonovation - could you please try toggling the Developer Tools in the View menu to see if they show any error logs (in red!) when this happens? Thanks!

**Comment by torbenbn** [comment]
@olensmar This is what I see in the JS console after initial load and the main pane turning black: 

```
ENOENT: no such file or directory, stat ''
loadContexts @ loadKubeConfig.ts:102
2react-dom.production.min.js:216 TypeError: Cannot set properties of undefined (setting 'cluster')
The error may be correlated with this previous error:
TypeError: Cannot set properties of undefined (setting 'cluster')
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:320657:21
    at Array.forEach (<anonymous>)
    at Function.unflatten (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:320626:23)
    at mergeConfigs (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:49171:237)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48812:3744
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48735:25
    at memoized (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48643:20)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48749:40
    at Object.memoized [as current] (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48643:20)
    at Object.checkForUpdates [as onStateChange] (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:621792:48)


    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:320657:21
    at Array.forEach (<anonymous>)
    at Function.unflatten (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:320626:23)
    at mergeConfigs (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:49171:237)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48812:3744
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48735:25
    at memoized (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48643:20)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48749:40
    at memoized (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48643:20)
    at useSelectorWithStoreAndSubscription (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:621759:30)
Ni @ react-dom.production.min.js:216
loadKubeConfig.ts:31 [loadContexts]: Cannot set properties of undefined (setting 'cluster')
The error may be correlated with this previous error:
TypeError: Cannot set properties of undefined (setting 'cluster')
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:320657:21
    at Array.forEach (<anonymous>)
    at Function.unflatten (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:320626:23)
    at mergeConfigs (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:49171:237)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48812:3744
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48735:25
    at memoized (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48643:20)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48749:40
    at Object.memoized [as current] (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:48643:20)
    at Object.checkForUpdates [as onStateChange] (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:621792:48)


showError @ loadKubeConfig.ts:31
DevTools failed to load source map: Could not parse content for file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/preload.js.map: Unexpected end of JSON input
```
Let me know if there is anything else I can look for.

/Torben

**Comment by olensmar** [comment]
Fantastic @torbenbn - I think that's just what we needed! thank you!
