### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [kubeshop/monokle#2041]
**Describe the bug**

**Steps to reproduce**

**Stacktrace** 

 ```
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
 TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:323:9)
    at Base64Input (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:12667:5570)
    at Ch (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:631688:7)
    at li (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:632332:7)
    at ck (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:634791:86)
    at bk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:634203:11)
    at ak (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:634195:23)
    at Tj (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:634179:5)
    at Lj (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:633901:28)
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:630761:18
    at exports.unstable_runWithPriority (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:655361:12)
    at gg (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:630732:10)
    at jg (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:630757:7)
    at ig (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:630747:3)
    at Wj (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:633932:30)
    at Object.notify (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:639661:7)
    at Object.notifyNestedSubs (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:639731:15)
    at handleChangeWrapper (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:639736:20)
    at dispatch (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:643977:7)
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:58045:790
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:253065:16
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:255538:20
    at dispatch (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:644361:28)
    at processSectionBlueprints (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:58045:635)
```

**Comment by topliceanurazvan** [comment]
Hello @xxxvik-xakerxxx , thank you for reporting this crash!
If possible, could you please help us with some more details of how this happened and how it can be reproduced?

**Comment by chargio** [comment]
Closing the issue as it is stalled
