### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by megaterrarc** [kubeshop/monokle#2100]
**Describe the bug**

**Steps to reproduce**

**Stacktrace** 

 ```
The "path" argument must be of type string. Received undefined
 TypeError: The "path" argument must be of type string. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.basename (node:path:752:5)
    at isKustomizationFilePath (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:53348:229)
    at isKustomizationFile (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:53350:59)
    at TreeItem (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:29791:5955)
    at Ch (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:614515:7)
    at li (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:615159:7)
    at ck (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:617618:86)
    at bk (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:617030:11)
    at ak (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:617022:23)
    at Tj (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:617006:5)
    at Lj (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:616728:28)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:613588:18
    at exports.unstable_runWithPriority (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:637213:12)
    at gg (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:613559:10)
    at jg (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:613584:7)
    at ig (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:613574:3)
    at Wj (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:616759:30)
    at Object.notify (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:622585:7)
    at Object.notifyNestedSubs (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:622657:15)
    at handleChangeWrapper (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:622662:20)
    at dispatch (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:626487:7)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:53936:790
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:247627:16
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:250100:20
    at dispatch (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:626871:28)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:249326:19
    at step (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:247759:17)
    at Object.next (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:247690:14)
    at fulfilled (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:247815:24)
```

**Comment by erdkse** [comment]
Thank you for reporting this bug @megaterrarc, we fixed it and most likely today we will release a new patch version with this fix.
