### ISSUE TITLE
Error opening monokle.app using MacOS Monterey

### ISSUE THREAD

**Issue by paivaric** [kubeshop/monokle#2309]
**Describe the bug**
Error opening monokle.app using MacOS Monterey

**To Reproduce**
1. Click to open monokle.app

**Expected behavior**
It should open

**Screenshots**
Uncaught Exception:
SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at Object.<anonymous> (/Applications/Monokle.app/Contents/Resources/app.asar/build/src/redux/services/schema.js:41:35)
at Module._compile (node:internal/modules/cjs/loader:1118:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/Applications/Monokle.app/Contents/Resources/app.asar/build/src/kindhandlers/common/customObjectKindHandler.js:36:18)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Monterey

**Additional context**
no

**Comment by erdkse** [comment]
Hey @paivaric , thank you for reporting this issue. Could you please tell me what version of Monokle you are using?

**Comment by chargio** [comment]
Hey @paivaric Are you still finding this issue?

**Comment by olensmar** [comment]
closing as stale - @paivaric please let us know if you are still getting this with 2.X
