### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by yashraj077** [kubeshop/monokle#2310]
**Describe the bug**

**Steps to reproduce**

**Stacktrace** 

 ```
Cannot read properties of undefined (reading '0')
 TypeError: Cannot read properties of undefined (reading '0')
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:49776:2196
    at Object.useMemo (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:608054:9)
    at exports.useMemo (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:618356:14)
    at ResourceKindContextMenuWrapper (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:49776:1831)
    at Ch (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:607633:7)
    at ck (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:610674:11)
    at bk (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:610148:11)
    at ak (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:610140:23)
    at Tj (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:610124:5)
    at Lj (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:609846:28)
```

**Comment by olensmar** [comment]
thanks for reporting @yashraj077 - do you recall what you were doing in Monokle when this happened?

**Comment by yashraj077** [comment]
@olensmar I was trying to install Monokle IDE on ubuntu but it failed with above error.

**Comment by olensmar** [comment]
Thanks @yashraj077 - digging in...

**Comment by topliceanurazvan** [comment]
Hello @yashraj077, 

We've been investigating the problem you had and it should be fixed in our latest nightly build https://github.com/kubeshop/monokle/releases/tag/v1.10.4-nightly-2022-09-13.0. 

Could you please test it and let us know if everything is working fine?

**Comment by chargio** [comment]
Closing this as there is no additional comment from users
