### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by vvatlin** [kubeshop/monokle#2523]
**Describe the bug**

**Steps to reproduce**

**Stacktrace** 

 ```
ModelService: Cannot add model because it already exists!
 Error: ModelService: Cannot add model because it already exists!
    at ModelServiceImpl._createModelData (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:475850:13)
    at ModelServiceImpl.createModel (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:475862:24)
    at doCreateModel (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:682518:23)
    at createTextModel (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:682508:12)
    at Object.createModel (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:693929:10)
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:29325:278
    at fk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:613569:19)
    at exports.unstable_runWithPriority (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:633411:12)
    at gg (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:609713:10)
    at Oj (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:613515:12)
```

**Comment by topliceanurazvan** [comment]
Hello @vvatlin,

Thank you for this report. This issues has been fixed, here you can find our latest nightly build https://github.com/kubeshop/monokle/releases/tag/v1.11.1-nightly-2022-10-10.0. 

Soon we will release a patch version that contains improvements & bug fixes, which will update your Monokle app automatically.

**Comment by topliceanurazvan** [comment]
Hello @vvatlin,

We've release 1.11.1 - https://github.com/kubeshop/monokle/releases/tag/v1.11.1. Please let us know if you're problem was fixed.
