### ISSUE TITLE
[crash] Side by side editors crashing

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#2580]
**Describe the bug**
In the installed 1.11.1 version, whenever I click on the Side by Side editors, I get the error below.
I tried it on multiple resources with different kinds and I received the same error.

**Stacktrace** 

 ```
Cannot read properties of null (reading 'getValue')
 TypeError: Cannot read properties of null (reading 'getValue')
    at MonacoEditor.componentDidUpdate (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:620110:64)
    at Yi (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:613882:141)
    at dk (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:615093:19)
    at exports.unstable_runWithPriority (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:635069:12)
    at gg (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:611359:10)
    at Uj (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:614887:3)
    at Lj (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:614534:3)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:611388:18
    at exports.unstable_runWithPriority (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:635069:12)
    at gg (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:611359:10)
```

**Comment by topliceanurazvan** [comment]
https://github.com/kubeshop/monokle/pull/2572 - fixed
