### ISSUE TITLE
A JavaScript error occurred in the main process - Apple M1

### ISSUE THREAD

**Issue by bygui86** [kubeshop/monokle#2652]
**Describe the bug**
Monokle is not able to start on MacBookPro with Apple Silicon M1, presenting following error:
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Command failed with ENOENT: /usr/local/bin/zsh -ilc echo -n "_SHELL_ENV_DELIMITER_"; env; echo -n "_SHELL_ENV_DELIMITER_"; exit
spawnSync /usr/local/bin/zsh ENOENT
at Object.spawnSync (node:internal/child_process:1111:20)
at Object.spawnSync (node:child_process:823:24)
at module.exports.sync (/Applications/Monokle.app/Contents/Resources/app.asar/node_modules/execa/index.js:174:25)
at shellEnvSync (/Applications/Monokle.app/Contents/Resources/app.asar/build/src/utils/env.js:45:44)
at getMainProcessEnv (/Applications/Monokle.app/Contents/Resources/app.asar/build/src/utils/env.js:61:26)
at getStaticResourcePath (/Applications/Monokle.app/Contents/Resources/app.asar/build/src/redux/services/index.js:14:56)
at loadResource (/Applications/Monokle.app/Contents/Resources/app.asar/build/src/redux/services/index.js:27:32)
at Object.<anonymous> (/Applications/Monokle.app/Contents/Resources/app.asar/build/src/redux/services/schema.js:41:69)
at Module._compile (node:internal/modules/cjs/loader:1118:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
```

**To Reproduce**
1. Download Monokle from official website or from GitHub official repo
2. Open dmg or extract zip file
3. Move Monokle.app to Applicatons folder
4. Open Monokle as every other mac app

**Expected behavior**
Monokle to start properly.

**Screenshots**
<img width="266" alt="Screenshot 2022-11-02 at 14 51 54" src="https://user-images.githubusercontent.com/22518997/199507108-c8aac425-9f6c-4806-9869-e47dc3d93fcc.png">

**Desktop (please complete the following information):**
- OS: MacOS Monterey
- Version 12.6
- Apple Silicon M1
- Monokle versions tested: 1.12.0, 1.11.1

**Comment by erdkse** [comment]
hey @bygui86 thank you for reporting this bug. I just wonder if you are using `zsh` on your system. Can you provide information, please?

**Comment by bygui86** [comment]
@erdkse yes I use zsh, here some info:
```
$ zsh --version
zsh 5.9 (arm-apple-darwin21.3.0)
```
do you need further info?

**Comment by bygui86** [comment]
Any news here?

**Comment by erdkse** [comment]
hey @bygui86, we investigated the issue but couldn't find a reason to cause it, If you have time could you please have a video meeting with me so I can see what is going on easier? This is my discord id, please contact to me `erdkse#6364`

**Comment by bygui86** [comment]
@erdkse I can find the time but I don't use Discord, what about Slack or scheduling an event in Google Calendar?

**Comment by erdkse** [comment]
Certo! I just invited you to a meeting! Please feel free to redefine the date and time.

**Comment by chargio** [comment]
it is working for me and @devcatalin  and we both have M1, let me know if I need to jump into the call with you

**Comment by erdkse** [comment]
I have M1 and it is working well for me too, I invited you both @chargio

**Comment by bygui86** [comment]
thanks guys
