### ISSUE TITLE
Monokle installed from .deb not starting

### ISSUE THREAD

**Issue by samuelverstraete** [kubeshop/monokle#3053]
**Describe the bug**
I installed 1.13.4 .deb file on my Ubuntu system. Monokle does not start.

On the cli i find this:
```
$ Monokle 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'split')
    at parseEnv (/opt/Monokle/resources/app.asar/build/src/utils/env.js:32:9)
    at shellEnvSync (/opt/Monokle/resources/app.asar/build/src/utils/env.js:46:16)
    at getMainProcessEnv (/opt/Monokle/resources/app.asar/build/src/utils/env.js:61:26)
    at getStaticResourcePath (/opt/Monokle/resources/app.asar/build/src/redux/services/index.js:14:56)
    at loadResource (/opt/Monokle/resources/app.asar/build/src/redux/services/index.js:27:32)
    at Object.<anonymous> (/opt/Monokle/resources/app.asar/build/src/redux/services/schema.js:42:69)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
```

**To Reproduce**
install & run Monokle

**Expected behavior**
It should not crash 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.10

**Additional context**

**Comment by erdkse** [comment]
hey @samuelverstraete , thank you for reporting this bug. I have some questions for you; 

* How did you download the deb file? Did you download it from our releases on Github?
* Could you also try running the binary by clicking on it, instead running it on CLI?

We will try to come up with a fix as soon as possible after we get these pieces of information, thank you again.

**Comment by samuelverstraete** [comment]
- I downloaded a deb file from the website and from the github page. both gave the same result.
- I initially tried just starting Monokle from my start menu (which is what I guess you mean by 'clicking' it). The only thing that happened was that my laptop starting making a whole lot of noise. To figure out what went wrong i then started it by the CLI...
