### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by gajendran-egov** [kubeshop/monokle#3316]
**Describe the bug**

**Steps to reproduce**

**Stacktrace** 

 ```
Cannot read properties of undefined (reading 'currentContext')
 TypeError: Cannot read properties of undefined (reading 'currentContext')
    at DashboardPane (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:110335:1475)
    at Xh (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:64935)
    at Wk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:118200)
    at Vk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:113844)
    at Uk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:113773)
    at Jk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:113630)
    at Fk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:110727)
    at jg (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:48408)
    at Rk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:111039)
    at Object.notify (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92479:136)
    at Object.notifyNestedSubs (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92479:1033)
    at handleChangeWrapper (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92479:1118)
    at dispatch (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93120:479)
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:124464:769
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:37731:8
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:37766:7390
    at dispatch (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93247:419)
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:37760:4280
    at step (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:37735:1665)
    at Object.next (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:37735:918)
    at fulfilled (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:37735:2896)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by topliceanurazvan** [comment]
Hey @gajendran-egov, thank you for reporting this! 🙌🏻 

Can you help us with some more information? Did you do any specific actions in order to be given this error?
