### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by clcc2019** [kubeshop/monokle#3335]
**Describe the bug**

**Steps to reproduce**

**Stacktrace** 

 ```
Cannot read properties of null (reading 'pushEditOperations')
 TypeError: Cannot read properties of null (reading 'pushEditOperations')
    at file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92380:7
    at Rj (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:98138)
    at Ik (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:116508)
    at Fk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:110667)
    at jg (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:48408)
    at Rk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:111039)
    at Jb (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:16237)
    at hd (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:40639)
    at fd (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:24722)
    at ed (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:91839:24506)
```

**Comment by mortada-codes** [comment]
Hey @clcc2019 , thank you for reporting this! 🙌🏻

Can you help us with some more information? Could you let me know if you did any specific actions to be given this error?

**Comment by topliceanurazvan** [comment]
Hello @clcc2019,

The problem that you have has been addressed in this PR https://github.com/kubeshop/monokle/pull/3337. We are currently working on releasing a new patch that will include the fix. After the release, we would appreciate it if you could confirm whether the issue has been resolved.
