### ISSUE TITLE
Crash when selecting cluster resource in list of resources

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3762]
**Describe the bug**

**Steps to reproduce**

not sure - i was just browsing resources from the cluster dashboard

**Stacktrace** 

 ```
Objects are not valid as a React child (found: [object Date]). If you meant to render a collection of children, use an array instead.
 Error: Objects are not valid as a React child (found: [object Date]). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:3000/bundle.main.js:730362:13)
    at createChild (http://localhost:3000/bundle.main.js:730643:11)
    at reconcileChildrenArray (http://localhost:3000/bundle.main.js:730902:29)
    at reconcileChildFibers (http://localhost:3000/bundle.main.js:731332:20)
    at reconcileChildren (http://localhost:3000/bundle.main.js:734618:32)
    at updateFragment (http://localhost:3000/bundle.main.js:734950:7)
    at beginWork (http://localhost:3000/bundle.main.js:737002:18)
    at beginWork$1 (http://localhost:3000/bundle.main.js:742711:18)
    at performUnitOfWork (http://localhost:3000/bundle.main.js:741869:16)
    at workLoopSync (http://localhost:3000/bundle.main.js:741782:9)
```

**Comment by olensmar** [comment]
this happens when clicking a resource in a list of resources - i.e. to open the resource overview panel... although I can't tell you for which resources..
