### ISSUE TITLE
[crash] Error trying to access the details of a pod in cluster mode

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3770]
**Describe the bug**
When accessing the details of a pod gets an error, instead of showing the information for the error

**Steps to reproduce**
1. Select the namespace
2. Select the pods
3. Select one specific pod (the problem does not happen all the time)

**Stacktrace** 

 ```
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Date%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Date%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:58098)
    at q (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:59952)
    at n (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:61120)
    at J (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:63215)
    at Yi (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:75067)
    at Wk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:120208)
    at Vk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:113844)
    at Uk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:113773)
    at Jk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:113630)
    at Fk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:110727)
    at jg (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:48408)
    at Rk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:111039)
    at Jb (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:16237)
    at hd (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:40639)
    at fd (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:24722)
    at ed (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:24506)
```

**Comment by olensmar** [comment]
please try with the main branch to see if this is fixed there

**Comment by topliceanurazvan** [comment]
https://github.com/kubeshop/monokle/pull/3767 fixed
