### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by saptarishi-das** [kubeshop/monokle#3814]
**Describe the bug**

**Steps to reproduce**

**Stacktrace** 

 ```
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Date%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Date%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:58098)
    at q (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:59952)
    at n (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:61120)
    at J (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:63215)
    at Yi (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:75067)
    at Wk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:120208)
    at Vk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:113844)
    at Uk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:113773)
    at Jk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:113630)
    at Fk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:110727)
    at jg (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:48408)
    at Rk (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:111039)
    at Jb (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:16237)
    at hd (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:40639)
    at fd (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:24722)
    at ed (file:///Applications/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:92515:24506)
```

**Comment by mortada-codes** [comment]
Thank you, @saptarishi-das, for reporting this issue. Can you please share the steps to reproduce it?

**Comment by saptarishi-das** [comment]
Hi,
1. I connectors to my awe cluster
2. Clicked on the pods in the left menu options
3. Clicked on one of the pods.

**Comment by topliceanurazvan** [comment]
Hey @saptarishi-das, this issue has been addressed in this [PR](https://github.com/kubeshop/monokle/issues/3770) and it will be included in our next patch release! Until then you can give it a try on our latest [nightly-build](https://github.com/kubeshop/monokle/releases/tag/v2.0.10-nightly-2023-04-28.0) and see how that behaves, the problem should be fixed!

**Comment by saptarishi-das** [comment]
Ok. This works now but the pod logs won’t load and neither the shell.

**Comment by olensmar** [comment]
thanks @saptarishi-das - digging in...
