### ISSUE TITLE
App can't find 'resources/schemas/k8sschemas.json' file after built.

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#388]
**Describe the bug**
After building the application, the app doesn't start due to this error.

**To Reproduce**
1.Build application
2. Install it.
3. Try to start the application.

**Expected behavior**
The app starts without an error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.6

**Additional context**

**Comment by canerbasaran** [comment]
$ ./Monokle-1.1.0.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open 'resources/schemas/k8sschemas.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
    at Object.loadResource (/tmp/.mount_MonoklPThbNz/resources/app.asar/build/src/redux/services/index.js:23:25)
    at Object.<anonymous> (/tmp/.mount_MonoklPThbNz/resources/app.asar/build/src/redux/services/schema.js:11:41)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
