### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by sanathwaghela** [kubeshop/monokle#3977]
**Describe the bug**

**Steps to reproduce**

**Stacktrace** 

 ```
Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
 Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at di (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:65518)
    at Object.si [as useRef] (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:68328)
    at exports.useRef (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:94333:6446)
    at exports.useSyncExternalStoreWithSelector (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:99126:325)
    at useSelector (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93821:342)
    at Object.icon (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:118058:1652)
    at O0 (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:36489:570)
    at Xh (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:64935)
    at dj (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:76756)
    at Wk (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:118977)
    at Vk (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:113844)
    at Uk (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:113773)
    at Jk (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:113630)
    at Fk (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:110727)
    at jg (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:48408)
    at Rk (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93158:111039)
    at Object.notify (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93852:136)
    at Object.notifyNestedSubs (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93852:1033)
    at handleChangeWrapper (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:93852:1118)
    at dispatch (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:94502:479)
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38234:8
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38269:7390
    at Object.dispatch (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:94629:419)
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:123448:10
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38263:3410
    at step (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38238:1665)
    at Object.next (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38238:918)
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38238:3174
    at new Promise (<anonymous>)
    at __async (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38238:2810)
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38263:2375
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38263:4343
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38233:8
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:38269:7390
    at Object.dispatch (file:///opt/Monokle/resources/app.asar/build/bundle.main.js:94629:419)
    at file:///opt/Monokle/resources/app.asar/build/bundle.main.js:123452:343
```

**Comment by olensmar** [comment]
Thanks for reporting this @sanathwaghela - could you please add some details on when this happened? How to reproduce? (if possible) thanks in advance!

**Comment by olensmar** [comment]
@sanathwaghela any input on how/when this happened?
