### ISSUE TITLE
[crash] Crashes when content is pasted into the manifest view

### ISSUE THREAD

**Issue by ClaasF** [kubeshop/monokle#4003]
**Describe the bug**

Monokle crashes, when pasting into the manifest view of a ConfigMap.

PS: I just filled out the auto-generated crash report, if there's more to report, let me know.

**Steps to reproduce**

* Connect to cluster
* Switch to a namespace
* Open Manifest-view of a ConfigMap
* Paste content
* Crash

**Stacktrace** 

 ```
Cannot read properties of undefined (reading 'namespace')
 TypeError: Cannot read properties of undefined (reading 'namespace')
    at file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:113248:1190
    at Array.filter (<anonymous>)
    at file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:113248:997
    at file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:113249:139
    at Object.Ci [as useMemo] (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:69355)
    at exports.useMemo (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:94333:6315)
    at Dashboard (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:113249:126)
    at Xh (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:64935)
    at dj (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:76756)
    at Wk (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:118977)
    at Vk (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:113844)
    at Uk (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:113773)
    at Jk (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:113630)
    at Fk (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:110727)
    at jg (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:48408)
    at Rk (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93158:111039)
    at Object.notify (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93852:136)
    at Object.notifyNestedSubs (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93852:1033)
    at handleChangeWrapper (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:93852:1118)
    at dispatch (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:94502:479)
    at file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:38234:8
    at file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:38269:7390
    at dispatch (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:94629:419)
    at file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:38263:4280
    at step (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:38238:1665)
    at Object.next (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:38238:918)
    at fulfilled (file:///private/var/folders/km/lf38m6ts5vv__6vcppskndw00000gn/T/AppTranslocation/E1592A08-AE8D-40B2-BEAC-80A5454C7E8A/d/Monokle.app/Contents/Resources/app.asar/build/bundle.main.js:38238:2896)
```

**Comment by olensmar** [comment]
Hi @ClaasF - huge thanks for reporting this - we'll have it fixed in the upcoming 2.2 release at the latest!

**Comment by devcatalin** [comment]
Hi @ClaasF , the error might've happened because there were some parsing problems of the object, which could happen when pasting code. We've now made the editor allow any changes on that YAML and not parse them until the changes are deployed to the cluster.
In addition, to avoid discarding unsaved changes, we'll now show a popup when the drawer is accidentally closed and there were any changes made to the YAML.
This will be available in the next 2.2 release which should be available later today or tomorrow.
Thank you!
