### ISSUE TITLE
[crash] Something went wrong

### ISSUE THREAD

**Issue by Exnadella** [kubeshop/monokle#4031]
**Describe the bug**
Not able to create the project.

**Steps to reproduce**
I have created a folder with the list of .yaml files and trying to load them as a folder and not able to load the files.

**Stacktrace** 

 ```
Cannot read properties of undefined (reading 'filePath')
 TypeError: Cannot read properties of undefined (reading 'filePath')
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:108586:195
    at a (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:99126:462)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:99126:681
    at Object.useSyncExternalStore (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:72013)
    at exports.useSyncExternalStore (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:94333:6580)
    at exports.useSyncExternalStoreWithSelector (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:99126:753)
    at useSelector (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93821:342)
    at SaveEditCommandModal (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:108586:134)
    at Xh (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:64935)
    at dj (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:76756)
    at Wk (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:118731)
    at Vk (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:113844)
    at Uk (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:113773)
    at Jk (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:113630)
    at Fk (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:110727)
    at jg (file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:48408)
    at file:///C:/Program%20Files/Kubeshop/Monokle/resources/app.asar/build/bundle.main.js:93158:108281
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
```

**Comment by Exnadella** [comment]
I also noticed that the desktop version keeps freezing and doesn't recover, so I had to end the Monokle desktop forcible.

**Comment by olensmar** [comment]
thanks for reporting this @Exnadella - which Monokle version are you using?

**Comment by Exnadella** [comment]
Hi @olensmar I am using monokle desktop and version it is displaying is 2.1.

**Comment by olensmar** [comment]
thanks @Exnadella - hm... how large are these files in total? is it possible for you to share the files you are loading (over a private channel of course) for debugging purposes?

**Comment by Exnadella** [comment]
Hi @olensmar There are 3 folders and 28 files, size on the disk is 8 KB.  with the .git folder we have 53 files and 17 folders.  We can have a call today to take a look.
