### ISSUE TITLE
Not supportive to Ubuntu Linux 

### ISSUE THREAD

**Issue by Anianonymous** [kubeshop/monokle#4176]
when I downloaded Monokle for linux, it shows platform is not supported!!

**Comment by sossaman** [comment]
Version 2.4.0/1 have the same behavior on my KDE Neon OS. After a few seconds from launch the screen turns white.
From an examination of the logs I found this error:
`[2023-10-17 15:09:01.546] [browser] [error] Error: Your platform is not supported
    at /tmp/.mount_Monokl5ghUcu/resources/app.asar/build/cli/terminal.js:14:20
    at new Promise (<anonymous>)
    at exports.default (/tmp/.mount_Monokl5ghUcu/resources/app.asar/build/cli/terminal.js:9:12)
    at Object.<anonymous> (/tmp/.mount_Monokl5ghUcu/resources/app.asar/build/electron/app/index.js:51:24)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)`

Previous versions work quite well, although unfortunately I notice high CPU usage

**Comment by Anianonymous** [comment]
> Version 2.4.0/1 have the same behavior on my KDE Neon OS. After a few seconds from launch the screen turns white. From an examination of the logs I found this error: `[2023-10-17 15:09:01.546] [browser] [error] Error: Your platform is not supported at /tmp/.mount_Monokl5ghUcu/resources/app.asar/build/cli/terminal.js:14:20 at new Promise (<anonymous>) at exports.default (/tmp/.mount_Monokl5ghUcu/resources/app.asar/build/cli/terminal.js:9:12) at Object.<anonymous> (/tmp/.mount_Monokl5ghUcu/resources/app.asar/build/electron/app/index.js:51:24) at Module._compile (node:internal/modules/cjs/loader:1271:14) at Object..js (node:internal/modules/cjs/loader:1326:10) at Module.load (node:internal/modules/cjs/loader:1126:32) at node:internal/modules/cjs/loader:967:12 at Function._load (node:electron/js2c/asar_bundle:2:13327) at Module.require (node:internal/modules/cjs/loader:1150:19)`
> 
> Previous versions work quite well, although unfortunately I notice high CPU usage

Thank you

**Comment by devcatalin** [comment]
Hi, sorry for the late reply!
We will try to reproduce the problem in order to fix it as soon as possible, sorry for the inconvenience.
Is there any additional info you could give us to help reproduce the problem?

**Comment by rsnyman** [comment]
I just installed Monokle 2.4.1 on Debian unstable, and ran into the same issue, it seems. I see the UI for a couple of seconds, and then everything goes white. If I click on the "Force Reload" option in the "View" menu, the UI comes up for a few seconds, and then goes back to white.

Here's the log file:

```
[2023-10-18 13:53:21.833] [browser] [info]  New Session.
[2023-10-18 13:53:21.837] [browser] [info]  New Installation.
[2023-10-18 13:53:21.912] [browser] [error] Error: Your platform is not supported
    at /opt/Monokle/resources/app.asar/build/cli/terminal.js:14:20
    at new Promise (<anonymous>)
    at exports.default (/opt/Monokle/resources/app.asar/build/cli/terminal.js:9:12)
    at Object.<anonymous> (/opt/Monokle/resources/app.asar/build/electron/app/index.js:51:24)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
[2023-10-18 13:53:22.009] [browser] [info]  info monokle 2.4.1 en-US undefined
[2023-10-18 13:53:24.429] [browser] [warn]  APPIMAGE env is not defined, current application is not an AppImage
[2023-10-18 13:53:24.430] [browser] [info]  checking dependencies with process path: /home/user/.krew/bin:/home/user/.local/bin:/home/user/bin:/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/games:/home/user/.local/bin:/home/user/.local/bin
[2023-10-18 13:53:24.517] [browser] [info]  checking dependencies with process path: /home/user/.krew/bin:/home/user/.local/bin:/home/user/bin:/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/games:/home/user/.local/bin:/home/user/.local/bin
[2023-10-18 13:53:30.249] [browser] [error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94576)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at dispatchToWindow (/opt/Monokle/resources/app.asar/build/electron/app/ipc/ipcMainRedux.js:18:24)
    at WebContents.<anonymous> (/opt/Monokle/resources/app.asar/build/electron/app/createWindow.js:208:9)
[2023-10-18 13:53:30.250] [browser] [error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94576)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at dispatchToWindow (/opt/Monokle/resources/app.asar/build/electron/app/ipc/ipcMainRedux.js:18:24)
    at WebContents.<anonymous> (/opt/Monokle/resources/app.asar/build/electron/app/createWindow.js:209:9)
[2023-10-18 13:53:30.250] [browser] [error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94576)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at dispatchToWindow (/opt/Monokle/resources/app.asar/build/electron/app/ipc/ipcMainRedux.js:18:24)
    at WebContents.<anonymous> (/opt/Monokle/resources/app.asar/build/electron/app/createWindow.js:210:9)
[2023-10-18 13:53:30.250] [browser] [error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94576)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at dispatchToWindow (/opt/Monokle/resources/app.asar/build/electron/app/ipc/ipcMainRedux.js:18:24)
    at WebContents.<anonymous> (/opt/Monokle/resources/app.asar/build/electron/app/createWindow.js:211:9)
[2023-10-18 13:53:48.405] [browser] [warn]  APPIMAGE env is not defined, current application is not an AppImage
[2023-10-18 13:53:48.406] [browser] [info]  checking dependencies with process path: /home/user/.krew/bin:/home/user/.local/bin:/home/user/bin:/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/games:/home/user/.local/bin:/home/user/.local/bin
[2023-10-18 13:53:48.488] [browser] [info]  checking dependencies with process path: /home/user/.krew/bin:/home/user/.local/bin:/home/user/bin:/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/games:/home/user/.local/bin:/home/user/.local/bin
[2023-10-18 13:55:41.160] [browser] [info]  New Session.
[2023-10-18 13:55:41.208] [browser] [error] Error: Your platform is not supported
    at /opt/Monokle/resources/app.asar/build/cli/terminal.js:14:20
    at new Promise (<anonymous>)
    at exports.default (/opt/Monokle/resources/app.asar/build/cli/terminal.js:9:12)
    at Object.<anonymous> (/opt/Monokle/resources/app.asar/build/electron/app/index.js:51:24)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
[2023-10-18 13:55:41.326] [browser] [info]  info monokle 2.4.1 en-US undefined
[2023-10-18 13:55:42.760] [browser] [warn]  APPIMAGE env is not defined, current application is not an AppImage
[2023-10-18 13:55:42.760] [browser] [info]  checking dependencies with process path: /home/user/.krew/bin:/home/user/.local/bin:/home/user/bin:/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/games:/home/user/.local/bin:/home/user/.local/bin
[2023-10-18 13:55:42.836] [browser] [info]  checking dependencies with process path: /home/user/.krew/bin:/home/user/.local/bin:/home/user/bin:/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/games:/home/user/.local/bin:/home/user/.local/bin
[2023-10-18 13:56:00.346] [browser] [error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94576)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at dispatchToWindow (/opt/Monokle/resources/app.asar/build/electron/app/ipc/ipcMainRedux.js:18:24)
    at click (/opt/Monokle/resources/app.asar/build/electron/app/menu.js:223:25)
    at MenuItem.click (node:electron/js2c/browser_init:2:30958)
    at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
[2023-10-18 13:56:02.047] [browser] [error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94576)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at dispatchToWindow (/opt/Monokle/resources/app.asar/build/electron/app/ipc/ipcMainRedux.js:18:24)
    at click (/opt/Monokle/resources/app.asar/build/electron/app/menu.js:223:25)
    at MenuItem.click (node:electron/js2c/browser_init:2:30958)
    at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
[2023-10-18 13:56:06.210] [browser] [warn]  APPIMAGE env is not defined, current application is not an AppImage
[2023-10-18 13:56:06.210] [browser] [info]  checking dependencies with process path: /home/user/.krew/bin:/home/user/.local/bin:/home/user/bin:/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/games:/home/user/.local/bin:/home/user/.local/bin
[2023-10-18 13:56:06.298] [browser] [info]  checking dependencies with process path: /home/user/.krew/bin:/home/user/.local/bin:/home/user/bin:/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/games:/home/user/.local/bin:/home/user/.local/bin
```

**Comment by devcatalin** [comment]
I've tested the `2.4.1` version on both Ubuntu and Debian with both `.deb` and `.AppImage` files and it seems to work fine.
I installed the `.deb` file using `sudo dpkg -i 'monokle.deb'` and for the `.AppImage` I have made it an executable with `chmod a+x 'monokle.AppImage'` , both seem to have worked for me.

But, I've also identified in the code where the error you're getting is coming from so I will make a patch for that error and create a new testing build. Will update this issue with the test build when it's done, hopefully it'll fix your problem.

**Comment by abegosum** [comment]
One more unable to use in Ubuntu here.  I get the same behavior described by @rsnyman - UI for about 1.5 seconds, then a white screen.  Reloading just repeats the same behavior.  This is using the x86-64 AppImage on Ubuntu 22.04.3, Wayland session.

**Comment by devcatalin** [comment]
I've made this test build https://github.com/kubeshop/monokle/releases/tag/test which includes a fix for the error shown in above. Could someone confirm if it works?

**Comment by devcatalin** [comment]
I'm rebuilding the release right now to include some updates to electron packages. The above URL should be available again in about 30-40 minutes.

**Comment by abegosum** [comment]
The test release is largely working for me, though helm seems to be missing in the AppImage.

**Comment by rsnyman** [comment]
Yup, it seems to be working for me.

Thanks @devcatalin for the super fast turnaround time!

**Comment by sossaman** [comment]
Hello,
the test build works also on my KDE Neon.
Thanks @devcatalin !

**Comment by Anianonymous** [comment]
> I've tested the `2.4.1` version on both Ubuntu and Debian with both `.deb` and `.AppImage` files and it seems to work fine. I installed the `.deb` file using `sudo dpkg -i 'monokle.deb'` and for the `.AppImage` I have made it an executable with `chmod a+x 'monokle.AppImage'` , both seem to have worked for me.
> 
> But, I've also identified in the code where the error you're getting is coming from so I will make a patch for that error and create a new testing build. Will update this issue with the test build when it's done, hopefully it'll fix your problem.

I installed .deb file using "sudo dpkg -i Monokle-linux-amd64.deb" then I opened Monokle its showing me this:
![image](https://github.com/kubeshop/monokle/assets/105560839/fe99ccf1-dbf4-4950-900f-9684f801a870)

**Comment by Anianonymous** [comment]
> I've made this test build https://github.com/kubeshop/monokle/releases/tag/test which includes a fix for the error shown in above. Could someone confirm if it works?

When I downloaded Monokle-linux-amd64.deb and when I opened, there's no content inside that file.

**Comment by Anianonymous** [comment]
> sudo dpkg -i

Hello, its largely working for me also.
Thanks @devcatalin

**Comment by Anianonymous** [comment]
> I've made this test build https://github.com/kubeshop/monokle/releases/tag/test which includes a fix for the error shown in above. Could someone confirm if it works?

Hello, its largely working for me also.
Thanks @devcatalin
