### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by pblgomez** [kubeshop/monokle#475]
**Describe the bug**
Fails to install

**To Reproduce**
npm install

**Expected behavior**
To install

**Screenshots**
```
> monokle@1.2.0 postinstall
> electron-builder install-app-deps

Error: Cannot find module 'fs/promises'
Require stack:
- /home/pbl/.local/cache/gits/kubeshop/monokle/node_modules/builder-util/out/fs.js
- /home/pbl/.local/cache/gits/kubeshop/monokle/node_modules/builder-util/out/util.js
- /home/pbl/.local/cache/gits/kubeshop/monokle/node_modules/electron-builder/out/cli/cli.js
- /home/pbl/.local/cache/gits/kubeshop/monokle/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pbl/.local/cache/gits/kubeshop/monokle/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pbl/.local/cache/gits/kubeshop/monokle/node_modules/builder-util/src/util.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code 1
npm ERR! path /home/pbl/.local/cache/gits/kubeshop/monokle
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Version: latest from git and 1.2.0 from source
 - Node: v12.21.0

**Additional context**
```
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated es6-tween@5.5.11: This project development suspended due of no support from community and no financial support to author
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

> monokle@1.2.0 postinstall
> electron-builder install-app-deps

Error: Cannot find module 'fs/promises'
Require stack:
- /home/pbl/.local/cache/gits/kubeshop/monokle-1.2.0/node_modules/builder-util/out/fs.js
- /home/pbl/.local/cache/gits/kubeshop/monokle-1.2.0/node_modules/builder-util/out/util.js
- /home/pbl/.local/cache/gits/kubeshop/monokle-1.2.0/node_modules/electron-builder/out/cli/cli.js
- /home/pbl/.local/cache/gits/kubeshop/monokle-1.2.0/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pbl/.local/cache/gits/kubeshop/monokle-1.2.0/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pbl/.local/cache/gits/kubeshop/monokle-1.2.0/node_modules/builder-util/src/util.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code 1
npm ERR! path /home/pbl/.local/cache/gits/kubeshop/monokle-1.2.0
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pbl/.npm/_logs/2021-10-05T09_07_54_357Z-debug.log
```

**Comment by olensmar** [comment]
hi! thanks for this - would it be possible for you to try with

node-version = 16.10.0
npm-version = 7.24.0

to see if that helps!?

**Comment by pblgomez** [comment]
Thanks, it does install with: v14.18.0 and npm 7.24.2.

**Comment by olensmar** [comment]
Great! Please let us know if you bump into any other issues!

**Comment by pblgomez** [comment]
Have you though about AppImage or any other packaging solution?

**Comment by olensmar** [comment]
electron-builder (which we're using under the hood) seems to support a bunch of packaging approaches for Linux - https://www.electron.build/configuration/linux - including AppImage - https://www.electron.build/configuration/appimage - we could provide any combination of these - just need to figure out which ones!
